resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: pull-request
  type: pull-request
  check_every: 1m
  webhook_token: ((webhook-token))
  source:
    base_branch: main
    repository: Ferlab-Ste-Justine/users-api-concourse
    access_token: ((git.access-token))
    states: ["OPEN"]
- name: git-users-api
  type: git
  icon: github
  check_every: 30s
  webhook_token: ((webhook-token))
  source:
    uri: git@github.com:Ferlab-Ste-Justine/users-api-concourse.git
    branch: ((branch))
    private_key: ((git.private-repo-key))
    ignore_paths: [ci/]
jobs:
- name: test-my-branch
  plan:
  - in_parallel:
    - get: pull-request
      trigger: true
    - get: git-users-api
  - task: test-echo
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: concourse/git-resource
      inputs:
        - name: git-users-api
      run:
        path: sh
        args:
        - -c
        - |
          echo "I am here now what's up" 